github:
  repos:
    - owner: "huggingface"
      repo: "transformers"
      path: "docs/source/en"
    # - owner: "huggingface"
    #   repo: "blog"
    #   path: "/"
summarizer_model: "sshleifer/distilbart-xsum-12-3"
# Other alternatives: "sshleifer/distilbart-cnn-12-6"
