github:
  repos:
    - owner: "huggingface"
      repo: "transformers"
      path: "docs/source/en"
    # - owner: "huggingface"
    #   repo: "blog"
    #   path: "/"
summarizer_model: "facebook/bart-large-cnn"
# Other alternatives: "sshleifer/distilbart-cnn-12-6", "sshleifer/distilbart-xsum-12-3"
resulting_jsonl_file: []

##### Config para text_processiong.yaml
recreate_chroma_db: false
embeddings_provider: cohere # puede ser "cohere"
embeddings_model: "embed-multilingual-v2.0" #text-embedding-ada-002 # con cohere puede ser "embed-multilingual-v2.0"
chroma_db_name: huggingface_docs_chroma
